MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/test/LIVA/ZWQ/CODE/TransReID_org/pretrained/jx_vit_base_p16_224-80ecf9dd.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('0, 1')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [16, 16]

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  SOURCES: ('market1501')
  ROOT_DIR: ('/home/test/LIVA/ZWQ/data')
  TARGETS: ('msmt17')
  # TRANSFORMS : ['random_flip', 'pad','random_crop', 'random_erase',  'color_jitter', 'bilateral']  
  TRANSFORMS : ['random_flip', 'pad','random_crop', 'random_erase',  'color_jitter']  

DATALOADER:
  # SAMPLER: 'softmax_triplet'
  SAMPLER: 'RandomIdentitySampler'
  # SAMPLER: 'RandomSampler'  
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 40
  BASE_LR: 0.008
  IMS_PER_BATCH: 256
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 2
  LOG_PERIOD: 50
  EVAL_PERIOD: 2
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: '../logs/market_msmt_base/model_best.pth.tar'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: '../logs/market_msmt_base'





