MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'ViT-B-16'
  STRIDE_SIZE: [16, 16]
  ID_LOSS_WEIGHT : 1.0
  TRIPLET_LOSS_WEIGHT : 1.0
  DEVICE_ID: ('0, 1')

  CAPTION: False


INPUT:
  PERSON_REID: True
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  SOURCES: ('msmt17')
  # SOURCES: ['market1501']
  ROOT_DIR: ('/home/test/LIVA/ZWQ/data')
  TARGETS: ('cuhk03')
  # TRANSFORMS : ['random_flip', 'pad','random_crop', 'random_erase', 'sobel']
  # TRANSFORMS : ['random_flip', 'pad','random_crop', 'random_erase', 'bilateral', 'color_jitter']
  TRANSFORMS : ['random_flip', 'pad','random_crop', 'random_erase', 'color_jitter']
  # TRANSFORMS: ['bilateral']

DATALOADER:
  # SAMPLER: 'softmax_triplet' ######### transreid
  SAMPLER: 'RandomIdentitySampler' ######## deep
  # SAMPLER: 'RandomSampler'  
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  IMS_PER_BATCH: 256
  OPTIMIZER_NAME: "Adam"
  BASE_LR: 0.000005
  # BASE_LR: 0.000015
  # BASE_LR: 0.000012
  WARMUP_METHOD: 'linear'
  WARMUP_ITERS: 10
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY:  0.0001
  WEIGHT_DECAY_BIAS: 0.0001
  LARGE_FC_LR: False
  MAX_EPOCHS: 60
  CHECKPOINT_PERIOD: 2
  LOG_PERIOD: 50
  EVAL_PERIOD: 2
  BIAS_LR_FACTOR: 2
  
  STEPS: [30, 50]
  GAMMA: 0.1

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  # WEIGHT: '/home/test/LIVA/ZWQ/pretrained/msmt17/MSMT17_baseline_ViT-B-16_60.pth'
  WEIGHT: '../logs/msmtcuhk_clip-fixcap-2fusion-online/model_best.pth.tar'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

HDRNET:
  HDR_NET : False
  LUMA_BINS : 8
  CHANNEL_MULTIPLIER : 1
  SPATIAL_BIN : 8
  GUIDE_COMPLEXITY : 16
  NET_INPUT_SIZE : [256, 128]
  PRETRAIN_PATH : '../logs/hdr/transformer_epoch190.pth'

CLIP:
  TEXT_FEAT: True
  CAPTION: False
  TEXT_FEAT_PATH: '/home/test/LIVA/ZWQ/pretrained/text_features_12.pt'
  TEXT_FEAT_QUERY_PATH: '/home/test/LIVA/ZWQ/pretrained/text_features_prompt.pt'
  PROMPT: ["a person's nose", "a person's head", "a person's arms", "a person's eyes", "a person's ears", "a person's neck", "a person's hands", "a person's feet", "a person's clothes"]
COOP:
  CTX_INIT : 'a photo of'
  # CTX_INIT: ""
  CLASS_TOKEN_POSITION: 'end'
MAPLE:
  MAPLE_PROMPT : False
  N_CTX : 3
  CTX_INIT : "a photo of"
  PROMPT_DEPTH : 1
OUTPUT_DIR: '../logs/msmtcuhk_clip-fixcap-2fusion-online'


