MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/test/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'resnet50'
  NO_MARGIN: True
  DEVICE_ID: ('0, 1')
  STRIDE_SIZE: [16, 16]
INPUT:
  PERSON_REID: True
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  SOURCES: ('market1501')
  # SOURCES: ['market1501']
  ROOT_DIR: ('/home/test/LIVA/ZWQ/data')
  TARGETS: ('cuhk03')
  # TRANSFORMS : ['random_flip', 'pad','random_crop', 'random_erase', 'sobel']
  # TRANSFORMS : ['random_flip', 'pad','random_crop', 'random_erase', 'bilateral', 'color_jitter']
  TRANSFORMS : ['random_flip', 'pad','random_crop','color_jitter']
  # TRANSFORMS: ['bilateral']

DATALOADER:
  # SAMPLER: 'softmax_triplet' ######### transreid
  SAMPLER: 'RandomIdentitySampler' ######## deep
  # SAMPLER: 'RandomSampler'  
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  IMS_PER_BATCH: 96 # debug 
  OPTIMIZER_NAME: "Adam"
  # BASE_LR: 0.00005
  BASE_LR: 0.000008
  WARMUP_METHOD: 'linear'
  WARMUP_ITERS: 20
  WARMUP_FACTOR: 0.01
  WEIGHT_DECAY:  0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  LARGE_FC_LR: False
  MAX_EPOCHS: 280
  CHECKPOINT_PERIOD: 20
  LOG_PERIOD: 20
  EVAL_PERIOD: 20
  BIAS_LR_FACTOR: 2
  
  STEPS: [40,80,120,160,200,240,280]
  GAMMA: 0.5

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: '/home/test/LIVA/ZWQ/CODE/Test/logs/resnet_snr_mar2cuhk/model_best.pth.tar'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
OUTPUT_DIR: '/home/test/LIVA/ZWQ/CODE/Test/logs/resnet_snr_mar2cuhk'


